maps/urls.py
from django.urls import path 
from .views import * 

app_name = 'maps' 

urlpatterns = [
    path('search', search_with_map, name='search-with-map'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('property/', include('property.urls', namespace='property')),
    path('', include('pages.urls', namespace='pages')), 
    path('maps/', include('maps.urls', namespace='maps')), 
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path 
from .views import * 

app_name = 'property' 

urlpatterns = [
    path('<str:number>/details/', property_details, name='property-details'), 
    path('add-property/', add_property, name='add-property'), 
    path('add-property/rent/apartment/', add_apartment_rent, name='add-apartment-rent'), 
    path('add-property/rent/floor/', add_floor_rent, name='add-floor-rent'),  
    path('add-property/rent/villa/', add_villa_rent, name='add-villa-rent'),  
    path('add-property/rent/shop/', add_shop_rent, name='add-shop-rent'),  
    path('add-property/rent/rest-house/', add_rest_house_rent, name='add-rest-house-rent'),  
    path('add-property/rent/building/', add_building_rent, name='add-building-rent'),  
]

property/views.py
from django.shortcuts import render, redirect
from .models import * 

# Create your views here.

def property_details(request, number): 
    property = ApartmentRent.objects.get(number=number) 
     
    context=  {
        'property': property, 
    } 
    return render(request, 'property/property-details.html', context ) 


def add_property(request):
    context = {} 
    return render(request, 'property/add-property-interface.html', context)



## دوال الايجار
def add_apartment_rent(request): 
    ### variables to get from html template 
    # price 
    # space 
    # advertiser_relation 
    # exclusive 
    # street width 
    # room count 
    # lounges
    # bathrooms 
    # floor 
    # property_age 

    exclusive = 0 

    if request.POST: 
        price = request.POST.get('price-input') 
        space = request.POST.get('space-input') 
        street_width = request.POST.get('street-width-input') 
        advertiser_relation = request.POST.get('advertiser_relation')
        if advertiser_relation != "مسوق": 
            exclusive = 0  
        else: 
            exclusive = request.POST.get('exclusive') 
        imgs = request.FILES.get('property__imgs')
        video = request.FILES.get('property__video')
        lat = request.POST.get('lat') 
        lng = request.POST.get('lng') 
        neighborhood = request.POST.get('neighborhood-input') 
        city= request.POST.get('city-input') 

        print(neighborhood) 
        print(city ) 

        # rooms = request.POST.get('room-input') 
        # if rooms == "" or rooms == 0 or rooms == None: 
        rooms = request.POST.get('extra-room-input') 
        if rooms == None or rooms == "" or rooms == 0: 
            rooms = request.POST.get("room-input")  
        
        
        lounges = request.POST.get('extra-lounges-input') 
        if lounges == None or lounges == "" or lounges == 0: 
            lounges = request.POST.get('lounges-input') 
        

        bathrooms = request.POST.get('extra-bathroom-input') 
        if bathrooms == None or bathrooms == '' or bathrooms == 0 : 
            bathrooms = request.POST.get('bathroom-input') 


        floor = request.POST.get('extra-floor-input') 
        if floor == None or floor == '' or floor == 0: 
            floor = request.POST.get('floor-input') 


        property_age = request.POST.get('extra-property-age-input') 
        if property_age == None or property_age == '' or property_age == 0: 
            property_age = request.POST.get('property-age-input') 
        
        description = request.POST.get('property__description__input') 
        rent_type_input = request.POST.get('rent_type_input') 
        try: 
            video = request.FILES['property__video'] 
        except: 
            video = None 
        print(video) 
        images = request.FILES.getlist('property__imgs') 
        images_status = request.POST.getlist('mainImage') 
        families = request.POST.get('families') 
        furnished = request.POST.get('furnished') 
        kitchen = request.POST.get('kitchen') 
        extenstion = request.POST.get('extenstion') 
        car_entrance = request.POST.get('car_entrance') 
        elevator = request.POST.get('elevator') 
        ac = request.POST.get('ac') 
        water_exist = request.POST.get('water_exist') 
        power_exist = request.POST.get('power_exist')         
        sanitation_exist = request.POST.get('sanitation_exist') 
        private_surface = request.POST.get('private_surface') 
        in_villa = request.POST.get('in_villa') 
        two_enternace = request.POST.get('two_enternace') 
        private_enternace = request.POST.get('private_enternace') 

        features = [
            families, 
            furnished, 
            kitchen, extenstion, 
            car_entrance, 
            elevator, 
            ac, 
            water_exist,
            power_exist, 
            sanitation_exist, 
            private_surface, in_villa, two_enternace, private_enternace
        ]


        for i in range(len(features)): 
            if features[i] == 'on': 
                features[i] = 1 
            else: 
                features[i] = 0 
        


        apartment = ApartmentRent.objects.create(
            street_width= street_width, 
            description = description, 
            price= price, 
            space=space, 
            video= video,
            neighborhood= neighborhood, 
            city = city, 
            advertiser_relation= advertiser_relation, 
            exclusive = exclusive, 
            rooms = rooms, 
            lounges = lounges, 
            bathroom = bathrooms, 
            floor = floor , 
            property_age = property_age, 
            rent_type = rent_type_input, 
            lat = lat, 
            lng=lng ,
            families = features[0], 
            furnished = features[1], 
            kitchen = features[2], 
            extenstion = features[3], 
            car_entrance = features[4], 
            elevator = features[5], 
            ac = features[6] , 
            water_exist = features[7], 
            power_exist = features[8], 
            sanitation_exist = features[9], 
            private_surface = features[10], 
            in_villa = features[11], 
            two_enternace = features[12], 
            private_enternace = features[13]
        )

        for i in range(len(images)): 
            ApartmentRentImage.objects.create(
                ad = apartment, 
                img = images[i] , 
                main = images_status[i]
            ).save() 



        return redirect('/ad-uploaded/')
            

        # print(price)
        # print(space)
        # print(advertiser_relation)
        # print(exclusive)
        # print(imgs)
        # print(video)
        # print(lat)
        # print(lng)
        # print(rooms)
        # print(lounges)
        # print(bathrooms)
        # print(floor)
        # print(property_age)

    context = {} 
    return render(request, 'property/add-apartment-rent.html', context)



def add_floor_rent(request): 
    ### variables to get from html template 
    # price 
    # space 
    # advertiser_relation 
    # exclusive 
    # street width 
    # room count 
    # lounges
    # bathrooms 
    # floor 
    # property_age 

    exclusive = 0 

    if request.POST: 
        price = request.POST.get('price-input') 
        space = request.POST.get('space-input') 
        street_width = request.POST.get('street-width-input') 
        advertiser_relation = request.POST.get('advertiser_relation')
        if advertiser_relation != "مسوق": 
            exclusive = 0  
        else: 
            exclusive = request.POST.get('exclusive') 
        imgs = request.FILES.get('property__imgs')
        video = request.FILES.get('property__video')
        lat = request.POST.get('lat') 
        lng = request.POST.get('lng') 
        neighborhood = request.POST.get('neighborhood-input') 
        city= request.POST.get('city-input') 

        # rooms = request.POST.get('room-input') 
        # if rooms == "" or rooms == 0 or rooms == None: 
        rooms = request.POST.get('extra-room-input') 
        if rooms == None or rooms == "" or rooms == 0: 
            rooms = request.POST.get("room-input")  
        
        
        lounges = request.POST.get('extra-lounges-input') 
        if lounges == None or lounges == "" or lounges == 0: 
            lounges = request.POST.get('lounges-input') 
        

        bathrooms = request.POST.get('extra-bathroom-input') 
        if bathrooms == None or bathrooms == '' or bathrooms == 0 : 
            bathrooms = request.POST.get('bathroom-input') 


        floor = request.POST.get('extra-floor-input') 
        if floor == None or floor == '' or floor == 0: 
            floor = request.POST.get('floor-input') 


        property_age = request.POST.get('extra-property-age-input') 
        if property_age == None or property_age == '' or property_age == 0: 
            property_age = request.POST.get('property-age-input') 
        
        description = request.POST.get('property__description__input') 
        rent_type_input = request.POST.get('rent_type_input') 
        try: 
            video = request.FILES['property__video'] 
        except: 
            video = None 
        print(video) 
        images = request.FILES.getlist('property__imgs') 
        families = request.POST.get('families') 
        furnished = request.POST.get('furnished') 
        kitchen = request.POST.get('kitchen') 
        extenstion = request.POST.get('extenstion') 
        car_entrance = request.POST.get('car_entrance') 
        elevator = request.POST.get('elevator') 
        ac = request.POST.get('ac') 
        water_exist = request.POST.get('water_exist') 
        power_exist = request.POST.get('power_exist')         
        sanitation_exist = request.POST.get('sanitation_exist') 
        private_surface = request.POST.get('private_surface') 
        in_villa = request.POST.get('in_villa') 
        two_enternace = request.POST.get('two_enternace') 
        private_enternace = request.POST.get('private_enternace') 

        features = [
            families, 
            furnished, 
            kitchen, extenstion, 
            car_entrance, 
            elevator, 
            ac, 
            water_exist,
            power_exist, 
            sanitation_exist, 
            private_surface, in_villa, two_enternace, private_enternace
        ]


        for i in range(len(features)): 
            if features[i] == 'on': 
                features[i] = 1 
            else: 
                features[i] = 0 
        


        floor = FloorRent.objects.create(
            street_width= street_width, 
            description = description, 
            price= price, 
            space=space, 
            video= video, 
            advertiser_relation= advertiser_relation, 
            exclusive = exclusive, 

property/templates/property/add-property-interface.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
إضافة عقار
{% endblock title %}



{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/property/add-property-interface.css' %}">

{% endblock stylesheets %}




{% block content %}


<section class="content">



    <div class="section__heading">
        <p>قسم العقار</p>
    </div>

    <div class="wrapper">
        <div class="wrpper__heading">
            <div class="grid">
                <div class="item clicked" id="btn-get-all">الكل</div>
                <div class="item" id="btn-get-rent">للإيجار</div>
                <div class="item" id="btn-get-sale">للبيع</div>
            </div>
        </div>
        <div class="wrapper__content" id="all">
            <ul>
                <li><a href="{% url 'property:add-apartment-rent' %}" class="property_type_link">شقة للإيجار</a></li>
                <li><a href="{% url 'property:add-floor-rent' %}" class="property_type_link">دور للإيجار</a></li>
                <li><a href="{% url 'property:add-villa-rent' %}" class="property_type_link">فيلا للإيجار</a></li>
                <li><a href="{% url 'property:add-shop-rent' %}" class="property_type_link">محل للإيجار</a></li>
                <li><a href="{% url 'property:add-building-rent' %}" class="property_type_link">بيت للإيجار</a></li>
                <li><a href="{% url 'property:add-rest-house-rent' %}" class="property_type_link">استراحة للإيجار</a></li>
                <li><a href="#" class="property_type_link">مكتب تجاري للإيجار</a></li>
                <li><a href="#" class="property_type_link">أرض للإيجار</a></li>
                <li><a href="#" class="property_type_link">عمارة للإيجار</a></li>
                <li><a href="#" class="property_type_link">مستودع للإيجار</a></li>
                <li><a href="#" class="property_type_link">مخيم للإيجار</a></li>
                <li><a href="#" class="property_type_link">غرفة للإيجار</a></li>
                <li><a href="#" class="property_type_link">شقة مفروشة</a></li>
                <li><a href="#" class="property_type_link">شاليه للإيجار</a></li>
            </ul>
            <ul>
                <li><a href="#" class="property_type_link">شقة للبيع</a></li>
                <li><a href="#" class="property_type_link">دور للبيع</a></li>
                <li><a href="#" class="property_type_link">فيلا للبيع</a></li>
                <li><a href="#" class="property_type_link">محل للبيع</a></li>
                <li><a href="#" class="property_type_link">بيت للبيع</a></li>
                <li><a href="#" class="property_type_link">استراحة للبيع</a></li>
                <li><a href="#" class="property_type_link">مكتب تجاري للبيع</a></li>
                <li><a href="#" class="property_type_link">أرض للبيع</a></li>
                <li><a href="#" class="property_type_link">عمارة للبيع</a></li>
                <li><a href="#" class="property_type_link">مستودع للبيع</a></li>
                <li><a href="#" class="property_type_link">مخيم للبيع</a></li>
                <li><a href="#" class="property_type_link">غرفة للبيع</a></li>
                <li><a href="#" class="property_type_link">شقة مفروشة</a></li>
                <li><a href="#" class="property_type_link">شاليه للبيع</a></li>
            </ul>
        </div>
        <div class="wrapper__content" id="sale">
            <ul>
                <li><a href="#" class="property_type_link">شقة للبيع</a></li>
                <li><a href="#" class="property_type_link">دور للبيع</a></li>
                <li><a href="#" class="property_type_link">فيلا للبيع</a></li>
                <li><a href="#" class="property_type_link">محل للبيع</a></li>
                <li><a href="#" class="property_type_link">بيت للبيع</a></li>
                <li><a href="#" class="property_type_link">استراحة للبيع</a></li>
                <li><a href="#" class="property_type_link">مكتب تجاري للبيع</a></li>
                <li><a href="#" class="property_type_link">أرض للبيع</a></li>
                <li><a href="#" class="property_type_link">عمارة للبيع</a></li>
                <li><a href="#" class="property_type_link">مستودع للبيع</a></li>
                <li><a href="#" class="property_type_link">مخيم للبيع</a></li>
                <li><a href="#" class="property_type_link">غرفة للبيع</a></li>
                <li><a href="#" class="property_type_link">شقة مفروشة</a></li>
                <li><a href="#" class="property_type_link">شاليه للبيع</a></li>
            </ul>
        </div>
        <div class="wrapper__content" id="rent">
            <ul>
                <li><a href="{% url 'property:add-apartment-rent' %}" class="property_type_link">شقة للإيجار</a></li>
                <li><a href="{% url 'property:add-floor-rent' %}" class="property_type_link">دور للإيجار</a></li>
                <li><a href="{% url 'property:add-villa-rent' %}" class="property_type_link">فيلا للإيجار</a></li>
                <li><a href="{% url 'property:add-shop-rent' %}" class="property_type_link">محل للإيجار</a></li>
                <li><a href="{% url 'property:add-building-rent' %}" class="property_type_link">بيت للإيجار</a></li>
                <li><a href="{% url 'property:add-rest-house-rent' %}" class="property_type_link">استراحة للإيجار</a></li>
                <li><a href="#" class="property_type_link">مكتب تجاري للإيجار</a></li>
                <li><a href="#" class="property_type_link">أرض للإيجار</a></li>
                <li><a href="#" class="property_type_link">عمارة للإيجار</a></li>
                <li><a href="#" class="property_type_link">مستودع للإيجار</a></li>
                <li><a href="#" class="property_type_link">مخيم للإيجار</a></li>
                <li><a href="#" class="property_type_link">غرفة للإيجار</a></li>
                <li><a href="#" class="property_type_link">شقة مفروشة</a></li>
                <li><a href="#" class="property_type_link">شاليه للإيجار</a></li>
            </ul>
        </div>
    </div>



</section>

<script src="{% static 'js/property/add-property-interface.js' %}"></script>

{% endblock content %}

property/templates/property/add-shop-rent.html
{% extends 'base.html' %}
{% load static %}



{% block title %}
إضافة محل للإيجار
{% endblock title %}
    

{% block stylesheets %}


    <link rel="stylesheet" href="{% static 'css/property/add-apartment-rent.css' %}">
{% endblock stylesheets %}
    


{% block content %}

<input type="hidden" name="rent-shop">

<div class="container form-container">

    <!-- popup -->

    <div class="overlay-layer"></div>

    <div class="popup on-imgs-popup">
        <p>هل أنت متأكد من الاستمرار بدون إضافة صور؟</p>
        <div class="buttons">
            <a class="btn btn-solid" id="no-imgs-popup-yes-btn">نعم</a>
            <a class="btn btn-outline" id="no-imgs-popup-no-btn">لا</a>
        </div>
    </div>

    <section >

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="hidden" name="neighborhood-input">
        <input type="hidden" name="city-input">

        <div class="section__timeline">
            <div class="section__timeline__content">

                <div>المعلومات</div>
                <div>الصور</div>
                <div>الموقع</div>
                <div>التفاصيل</div>
                <div>المزايا</div>

            </div>

            <div class="section__timeline__progress">
                <div class="progress-container"></div>
            </div>

        </div>

        <div class="property__info">
            <!-- <div class="input" >
                <p class="input-label">عنوان الإعلان <span class="input-label-highlight"></span></p>
                <input type="text" name="title-input" placeholder="الرجاء كتابة عنوان الإعلان...">
            </div> -->


            <div class="input" >
                <p class="input-label">السعر <span class="input-label-highlight">(ريال سعودي)</span></p>
                <input type="text" name="price-input" placeholder="الرجاء كتابة السعر...">
            </div>

            <div class="input">
                <p class="input-label">المساحة <span class="input-label-highlight">(متر مربع)</span></p>
                <input type="text" name="space-input" placeholder="الرجاء كتابة المساحة...">
            </div>

            <input type="hidden" name="advertiser_relation" >
            <input type="hidden" name="exclusive">

            <!-- <div class="input">
                <p class="input-label">الطول <span class="input-label-highlight">(متر)</span></p>
                <input type="text" placeholder="الرجاء كتابة السعر...">
            </div>

            <div class="input">
                <p class="input-label">العرض <span class="input-label-highlight">(متر)</span></p>
                <input type="text" placeholder="الرجاء كتابة السعر...">
            </div> -->

            <!-- <div class="input">
                <p class="input-label">السعر <span class="input-label-highlight">(ريال سعودي)</span></p>
                <input type="text" placeholder="الرجاء كتابة السعر...">
            </div> -->

            <!-- <div class="box">
                <p>نوع الإيجار</p>
                <div class="grid rent-type">
                    <input type="hidden" name="rent_type_input">
                    <div class="item" data-value="monthly">شهري</div>
                    <div class="item" data-value="yearly">سنوي</div>
                </div>
            </div> -->
            <br>

            <div class="box">
                <p>علاقة المعلن بالعقار</p>
                <div class="grid" id="advertiser_relation_grid">
                    <input type="hidden" name="advertiser_relation_input">
                    <div class="item">مسوق</div>
                    <div class="item">مالك</div>
                    <div class="item">وكيل</div>
                </div>

                <div class="grid" id="markter-type-grid">
                    <input type="hidden" name="marketer_type_input">
                    <div class=" sub-item">حصري</div>
                    <div class="sub-item">غير حصري</div>
                </div>

            </div>



            <div class="property__info__next-prev next-prev">
                <a  class="btn-prev btn btn-solid-light">السابق</a>
                <a  class="btn-next btn btn-solid-success">التالي</a>
            </div>


        </div>

        <!-- هنا إضافة سلايدر الواجهة وكذلك في اضافة فيلا -->

        <div class="property__details">
            <div class="box" style="margin-top: 1rem;">
                <input type="hidden" name="street-width-input">
                <div class="info">
                    <p>عرض الشارع</p>
                    <p class="value">
                        <span name="street-width">0</span>
                        م
                    </p>
                </div>
                <div class="slider">
                    <input class="slider_input" type="range" max="100" value="0">
                </div>
            </div>


            


            <div class="box">
                <div class="info">
                    <p>عمر العقار</p>
                </div>
                <div class="grid property-age">
                    <input type="hidden" name="property-age-input">
                    <div class="item">جديد</div>
                    <div class="item">1</div>
                    <div class="item">2</div>
                    <div class="item">3</div>
                    <div class="item">4</div>
                    <div class="item item_more">
                        <select name="extra-property-age-input" id="custom_select">
                            <option disabled selected hidden>أكثر</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                            <option value="21">21</option>
                            <option value="22">22</option>
                            <option value="23">23</option>
                            <option value="24">24</option>
                            <option value="+25">+25</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="property__details__next-prev next-prev">
                <a  class="btn-prev btn btn-solid-light">السابق</a>
                <a  class="btn-next btn btn-solid-success">التالي</a>
            </div>

        </div>

        <div class="property__imgs">
            <div class="btn add-img button" >
                <input type="file" multiple name="property__imgs" accept="image/*" >
                <label >إضافة صور </label>
                <i class="fa-solid fa-camera"></i>
            </div>
            <div class="btn add-video button">
                <input type="file" name="property__video" accept="video/*" >
                <label >إضافة فيديو </label>
                <i class="fa-solid fa-video"></i>
            </div>

            <div class="preview_imgs_container">

            </div>


            <div class="preview_video_container">

            </div>

            <div class="property__imgs__next-prev next-prev">
                <a href="#" class="btn-prev btn btn-solid-light">السابق</a>
                <a href="#" class="btn-next btn btn-solid-success">التالي</a>
            </div>

        </div>



        <div class="property__features">
            <div class="property__description__container">
                <p>وصف العقار</p>
                <textarea placeholder="الرجاء كتابة وصف عن العقار" name="property__description__input" id="">
                </textarea>
            </div>

            <div class="property__features__container">
                <p>مزايا العقار</p>
                <div class="property__features__wrapper">



                    <div class="property__feature__item">
                        <label class="toggle-container">
                            <input type="checkbox" name="water_exist" class="toggle-switch">
                            <span class="toggle-circle"></span>
                        </label>
                        <p>توفر الماء</p>
                    </div>

                    <div class="property__feature__item">
                        <label class="toggle-container">
                            <input type="checkbox" name="power_exist" class="toggle-switch">
                            <span class="toggle-circle"></span>
                        </label>
                        <p>توفر الكهرباء</p>
                    </div>

                    <div class="property__feature__item">
                        <label class="toggle-container">
                            <input type="checkbox" name="sanitation_exist" class="toggle-switch">
                            <span class="toggle-circle"></span>
                        </label>
                        <p>توفر الصرف</p>
                    </div>

                </div>

                
                <div class="property__features__next-prev next-prev">
                    <a href="#" class="btn-prev btn btn-solid-light">السابق</a>
                    <button type="submit" class="btn-next btn btn-solid-success">رفع الإعلان</button>
                </div>

            </div>
        </div>


        <div class="property__location">

            <input type="hidden" name="lat" id="lat-input">
            <input type="hidden" name="lng" id="lng-input">
            
            <p class="property__location__heading">الرجاء تحديد الموقع الصحيح للعقار</p>
            <div class="map-container">
                <div id="map"></div>
                <a href="#" id="myLocationButton" class="btn btn-mylocation">
                    <i class="fa-solid fa-location-crosshairs"></i>
                    موقعي
                </a>
                <a href="#" class="btn btn-terrain">تضاريس</a>
            </div>

            <div class="property__location__next-prev next-prev">
                <a href="#" class="btn-prev btn btn-solid-light">السابق</a>
                <a href="#" class="btn-next btn btn-solid-success">التالي</a>
            </div>
        </div>

    </form>


    </section>



</div>


    <script src="{% static 'js/property/add-property-shop.js' %}"></script>
    
    <script>
        // JavaScript code to handle the toggle switch
        const toggleSwitchs = document.querySelectorAll('.toggle-switch');
        const toggleContainer = document.querySelector('.toggle-container');

        toggleSwitchs.forEach((toggleSwitch) => {
            toggleSwitch.addEventListener('change', function() {
                if (toggleSwitch.checked) {
                    toggleSwitch.parentElement.classList.add('checked');
                } else {
                    toggleSwitch.parentElement.classList.remove('checked');
                }
            });
        })

    </script>

    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDKt6ozfNbfbA7RIWbNeIvy3Rj4NT7RpO4&callback=initMap"></script>
    <script src="{% static 'js/property/init-map.js' %}"></script>


{% endblock content %}
    