maps/urls.py
from django.urls import path 
from .views import * 

app_name = 'maps' 

urlpatterns = [
    path('search', search_with_map, name='search-with-map'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('property/', include('property.urls', namespace='property')),
    path('', include('pages.urls', namespace='pages')), 
    path('maps/', include('maps.urls', namespace='maps')), 
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="المستخدم")
    image = models.ImageField(default='default.jpg', upload_to='profile_pics/', verbose_name='صورة الملف الشخصي', null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} Profile"
    

    class Meta:
        verbose_name='ملف شخصي'
        verbose_name_plural ='الملفات الشخصية'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(label="البريد الإلكتروني", widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='الاسم الأول', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="الاسم الأخير", widget=forms.TextInput(attrs={"class": "form-control"}))


    class Meta:
        model = User 
        fields = ["username", 'first_name', 'last_name', 'email']

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = Profile 
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from .forms import UserUpdateForm, UpdateProfileForm
from .models import Profile  
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def profile(request):
    user=  request.user 
    profile = Profile.objects.get(user=user) 
    user_update = UserUpdateForm(instance=user)
    profile_update = UpdateProfileForm(instance=profile)
    if request.POST: # Save
        user_update = UserUpdateForm(request.POST, instance=request.user)
        profile_update = UpdateProfileForm(request.POST, request.FILES, instance=profile)
        if user_update.is_valid() and profile_update.is_valid():
            # user_update.save(commit=False)
            user_update.save()

            profile_update.save(commit=False) 
            profile_update.user = request.user 
            profile_update.save()
            print('Saved !!!')
            print('save successfully !') # test code 
    else: # Show
        user_update = UserUpdateForm(instance=user)
        profile_update = UpdateProfileForm(instance=profile)

    context = {
        'user_update': user_update,
        'profile_update': profile_update, 
    }
    return render(request, 'users/profile.html', context)

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
الملف الشخصي
{% endblock title %}


{% block stylesheets %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/users/main.css' %}">

<style>
  .public-information, .security {
    padding: 1rem;
  }
  .info div {
    padding-top: 1rem;
  }
  .info div h3 {
    padding-bottom: .5rem;
  }
</style>
{% endblock stylesheets %}


{% block content %}
<div class="container">
  <h1>حسابك</h1>
  <p>قم بإدارة التفاصيل الخاصة بك، وعرض حالتك وكلمة المرور الخاصة بك</p>

  <div class="public-information">
    <h2>معلومات عامة</h2>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          {{user_update.username|as_crispy_field}}
        </div>
        <div class="col-sm-6">
          {{user_update.email|as_crispy_field}}
        </div>
      </div>
      
      <div class="row mt-3">
        <div class="col-sm-6">
          {{user_update.first_name|as_crispy_field}}
        </div>
        <div class="col-sm-6">
          {{user_update.last_name|as_crispy_field}}
        </div>
      </div>
    </div>

        <br>
        <div class="grid">
          <div class="item" style="display: flex; justify-content: space-between; width: 100%;">
            <button type="submit" class="btn btn-solid">تحديث المعلومات</button>
            <a href="{% url 'account_reset_password' %}" class="btn btn-outline">تغيير كلمة المرور</a>
          </div>
          <div class="item"></div>
          <div class="item"></div>
        </div>
      </form>
      <!-- <a href="#" class="update">تحديث المعلومات</a> -->
      <br>
      <!-- <a href="#" class="btn btn-solid-dark">تحديث المعلومات</a> -->
  </div>

</div>


<script>


document.querySelector('#id_username').setAttribute('placeholder', 'اسم المستخدم')
document.querySelector('#id_email').setAttribute('placeholder', 'البريد الإلكتروني') 
document.querySelector('#id_first_name').setAttribute('placeholder', 'الاسم الأول') 
document.querySelector('#id_last_name').setAttribute('placeholder', 'الاسم الأخير') 

</script>


{% endblock %}