maps/urls.py
from django.urls import path 
from .views import * 

app_name = 'maps' 

urlpatterns = [
    path('search', search_with_map, name='search-with-map'), 
]

pages/urls.py
from django.urls import path 
from .views import * 

app_name = 'pages'

urlpatterns = [
    path('', home, name='home'), 
    path('about/', about, name='about'), 
    path('contact/', contact, name='contact'), 
    path('request-contract/', request_contract, name='request-contract'), 
    path('ad-uploaded/', ad_uploaded, name='ad-uploaded'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('property/', include('property.urls', namespace='property')),
    path('', include('pages.urls', namespace='pages')), 
    path('maps/', include('maps.urls', namespace='maps')), 
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> 
        {% block title %}
        {% endblock title %}    
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/pages/main.css' %}">
    <link rel="icon" href="./assets/imgs/logo.jpeg"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet"> 
    
    {% block stylesheets %}
        
    {% endblock stylesheets %}
        

</head>
<body>
    <header>
        <div class="container">
            <div class="logo-container">
                <img src="{% static 'imgs/logo.jpeg' %}" alt="">
                <img src="{% static 'imgs/logoText-e961f794.png' %}" alt="">
            </div>
            <nav>
                <ul>
                    <li><a href="{% url 'pages:home' %}" class="list-item">الرئيسية</a></li>
                    <li><a href="#" class="list-item">أصحاب العقار</a></li>
                    <li><a href="{% url 'pages:request-contract' %}" class="list-item">طلب عقد إلكتروني</a></li>
                    <li><a href="#" class="list-item">تواصل معنا</a></li>
                    <li><a href="{% url 'pages:about' %}" class="list-item">من نحن</a></li>
                </ul>
            </nav>
            <nav>
                <ul>
                    
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:profile' %}" class="btn btn-solid">الملف الشخصي</a></li>
                    <li><a href="{% url 'account_logout' %}" class="btn btn-outline">تسجيل خروج</a></li>
                    {% else %}
                    <li><a href="#" class="btn btn-solid">إضافة عقار</a></li>
                    <li><a href="{% url 'account_login' %}" class="btn btn-outline">تسجيل دخول</a></li>
                    {% endif %}

                </ul>
            </nav>
            <a href="#" id="burger-menu">
                <i class="fa-solid fa-bars"></i>
            </a>
        </div>
    </header>

    <!-- MAIN -->

    
    {% block content %}
        
    {% endblock content %}
        

    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="footer-logo-container">
                    <img src="{% static 'imgs/logo-transparent.png' %}" alt="">
                </div>
                <!-- <div class="quick-links">
                    <h4>روابط سريعة</h4>

                    <ul>
                        <li><a href="#" class="list-item">الرئيسية</a></li>
                        <li><a href="#" class="list-item">أصحاب العقار</a></li>
                        <li><a href="#" class="list-item">طلب عقد إلكتروني</a></li>
                        <li><a href="#" class="list-item">تواصل معنا</a></li>
                        <li><a href="#" class="list-item">من نحن</a></li>
                    </ul>
                </div> -->
                <div class="social-media">
                    <h4>تابعنا على</h4>

                    <ul>
                        <li><a href="#" class="list-item social-link">
                            <i class="fa-brands fa-snapchat"></i>
                        </a></li>

                        <li><a href="#" class="list-item social-link">
                            <i class="fa-solid fa-phone"></i>
                        </a></li>
                        
                        <li><a href="#" class="list-item social-link">
                            <i class="fa-brands fa-whatsapp"></i>
                        </a></li>
                        
                        <li><a href="#" class="list-item social-link">
                            <i class="fa-brands fa-tiktok"></i>
                        </a></li>
                        
                        <li><a href="#" class="list-item social-link">
                            <i class="fa-solid fa-location-dot"></i>
                        </a></li>
                        
                    </ul>
                </div>
            </div>
            <div class="copyrights">
                مكتب البداح للعقارات © 2023 جميع الحقوق محفوظة
            </div>
        </div>
    </footer>



    <script>
        burgerMenu = document.querySelector('#burger-menu')
        let swiperMenu = document.querySelector('.mySwiper'); 


        burgerMenu.addEventListener('click', () => {
          document.querySelectorAll('header .container nav').forEach((nav) => {
            nav.classList.toggle('show');
          })
          swiperMenu.classList.toggle('hide'); 
        })


        document.querySelectorAll('textarea').forEach((item) => {
            item.value = "" ;
        })
    </script>

</body>
</html>